name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: ./test.sh
